language: python
python:
  - "3.5"
before_install:
  - pip install --upgrade setuptools --user python
install:
  - pip install -r requirements.txt
script:
  - pytest
deploy:
  provider: script
  script: sh deploy.sh
  on:
    branch: master