language: python
dist: trusty
sudo: required
addons:
  chrome: stable
python:
  - "3.5"
before_install:
  - sudo apt-get install chromium-chromedriver
install:
  - pip install -r requirements.txt
before_script:
  - export PATH=$PATH:/usr/lib/chromium-browser/
script:
  - pytest
deploy:
  provider: script
  script: sh deploy.sh
  on:
    branch: master